version: '3.8'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: seata
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev1234
    ports:
      - "3306:3306"
    volumes:
      - ../src/main/resources/sql:/docker-entrypoint-initdb.d